version: "3.7"

services:
  app:
    image: amir20/dozzle:v8.14.3
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: "simple"
      DOZZLE_REMOTE_AGENT: "100.87.63.211:7007,100.87.63.62:7007,100.87.23.15:7007,100.87.16.60:7007,100.87.145.127:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/data:/data
